### ISSUE TITLE
The export design decision...

### ISSUE THREAD

**Issue by ahkhanjani** [philihp/fast-shuffle#427]
This looks like a great library. I haven't used it yet and just started reading the documentation and it seems to be just what I needed. I'm assuming it doesn't mutate the original array which is nice.

Although, I'm here to state my personal opinion on one thing I just read which was shocking to me. The difference in behavior between the named and the default export is one of the worst design decisions I've ever seen. If you ever release a new major version, please consider using no default export and change the current default to a properly named one.

I'm still going to use the library though. Thanks for maintaining this

**Comment by philihp** [comment]
Ugh yeahhhh dude, I hate that too! Ugh, what was I thinking? Let's fix that!
