### ISSUE TITLE
Error with ramda package

### ISSUE THREAD

**Issue by Dylan190774** [philihp/fast-shuffle#580]
When I do `yarn run build`, I get a lot of the following warnings:

`"node_modules/ramda/src/index.js" contains an annotation that Rollup cannot interpret"`

I don't see this warning when I use `yarn run dev`.

`fast-shuffle` is the only package in my `package.json` that uses `ramda`.

Any way to avoid these messages?

**Comment by philihp** [comment]
looks like a problem with Rollup, no?  https://github.com/rollup/rollup/pull/5332 seems related, what version of Rollup are you using?

regardless, i'm happy to push out a new version of the library which might alleviate your problem.

**Comment by philihp** [comment]
Please try v`6.1.1`, i hope that fixes things for you!
